### ISSUE TITLE
wstest: 'FuzzingClientFactory' object has no attribute 'startedConnecting'

### ISSUE THREAD

**Issue by jchampio** [tavendo/AutobahnPython#500]
After upgrading to 0.10.8, wstest now fails for me with the following stack:
```
Traceback (most recent call last):
  File "/usr/local/bin/wstest", line 9, in <module>
    load_entry_point('autobahntestsuite==0.7.1', 'console_scripts', 'wstest')()
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/wstest.py", line 338, in run
    start(options, spec)
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/wstest.py", line 260, in start
    res = wstest.startService()
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/wstest.py", line 224, in startService
    return fuzzing.startClient(self.spec, debug = self.debug)
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/fuzzing.py", line 1274, in startClient
    factory = FuzzingClientFactory(spec, debug)
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/fuzzing.py", line 1196, in __init__
    connectWS(self)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 534, in connectWS
    conn = reactor.connectTCP(factory.host, factory.port, factory, timeout, bindAddress)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 496, in connectTCP
    c.connect()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1030, in connect
    self.factory.startedConnecting(self)
AttributeError: 'FuzzingClientFactory' object has no attribute 'startedConnecting'
```
It looks like this _might_ have something to do with commit 9f687490 and the switch from ClientFactory?

**Comment by oberstet** [comment]
Yes, `connectTCP` / `connectWS` is broken by above commit. If you need the testsuite, please use AutobahnPython 0.10.7 for now. Sorry.

```console
(python279_1)oberstet@thinkpad-t430s:~/scm/autobahn/AutobahnPython/examples/twisted/websocket/echo$ python server.py 
2015-09-15 01:32:55+0200 [-] Log opened.
2015-09-15 01:32:55+0200 [-] WebSocketServerFactory starting on 9000
2015-09-15 01:32:55+0200 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7fe6fa0b0b90>
```

and

```console
(python279_1)oberstet@thinkpad-t430s:~/scm/autobahn/AutobahnPython/examples/twisted/websocket/echo$ python client.py 
2015-09-15 01:33:06+0200 [-] Log opened.
2015-09-15 01:33:06+0200 [-] Starting factory <autobahn.twisted.websocket.WebSocketClientFactory object at 0x7f8319373b90>
2015-09-15 01:33:06+0200 [-] Traceback (most recent call last):
2015-09-15 01:33:06+0200 [-]   File "client.py", line 69, in <module>
2015-09-15 01:33:06+0200 [-]     reactor.connectTCP("127.0.0.1", 9000, factory)
2015-09-15 01:33:06+0200 [-]   File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 483, in connectTCP
2015-09-15 01:33:06+0200 [-]     c.connect()
2015-09-15 01:33:06+0200 [-]   File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/base.py", line 1051, in connect
2015-09-15 01:33:06+0200 [-]     self.factory.startedConnecting(self)
2015-09-15 01:33:06+0200 [-] AttributeError: 'WebSocketClientFactory' object has no attribute 'startedConnecting'
```

**Comment by oberstet** [comment]
@jchampio ok, I've pushed https://pypi.python.org/pypi/autobahntestsuite/0.7.2 and https://pypi.python.org/pypi/autobahn/0.10.9

You should be fine doing a: `pip install -U autobahntestsuite`

**Comment by jchampio** [comment]
Works great. Thanks for the quick turnaround!
