### ISSUE TITLE
Cleanup WAMP examples

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#304]
Now that the router code has moved to Crossbar.io, cleanup the examples ..

**Comment by JuliaRakitina** [comment]
So I tried example from WAMP twisted with python 3.4 and it failed because of Twisted not integrated with python 3.4, after that I tried asyncio basic example and it failed with 'module' object has no attribute 'RouterFactory' because "Now that the router code has moved to Crossbar.io" and Crossbar.io does not run with python 3.4 again because of Twisted. I wasted 1.5 hour just walking rounds (
Does it work with python 3 ? If no it should be in "requirements"

**Comment by goeddea** [comment]
We're sorry the examples haven't been updated yet.

Autobahn|Python works with Python 3.4 and asyncio. Our WAMP router implementation, Crossbar.io, where the router code has been moved from Autobahn|Python, requires Twisted,  and thus only works on Python 2.7. You can use this, with two Python versions installed (made easier using virtualenv), or, depending on the features you need, use another WAMP router (see the [WAMP implementations page](http://wamp.ws/implementations/))

For any example, the client components should work with Python 3.4.

If you run into more trouble, please tell us which example(s) you're primarily interested in, and we'll add adapting these to the top of our queue.

**Comment by oberstet** [comment]
@JuliaRakitina I am sorry for the mess. It is confusing, and we're working on improving things. The challenge is: Crossbar.io is moving fast, so we can't keep all examples in sync all the time, and also, WAMP is a growing ecosystem (not single vendor), so there are a lot of pieces involved etc etc

Regarding your concrete issue: you write app components in Python using AutobahnPython, and the latter supports all variants (http://autobahn.ws/python/installation.html#supported-configurations). To run your app, you then need a WAMP router. You should look at this as a "black box" (not caring how it is implemented). The easiest way to start without even installing Crossbar.io is by using our public demo Crossbar.io instance:

* URL: `wss://demo.crossbar.io/ws`
* Realm: `realm1`

**Comment by JuliaRakitina** [comment]
I got it already :) Finally moved project to python 2.7
Actually I couldn't run crossbar.io demos because "there is no demo template" Crossbar said. But I found a way it works in hello:python template. I dont know how to rename template yet, can I? If Crossbar  is "black box" and it automatically created project structure, can I rename folders in project(for example hello folder)?

**Comment by oberstet** [comment]
@JuliaRakitina All app templates other than "hello:XXX" have moved to https://github.com/crossbario/crossbarexamples - it just got too many. And yes, you can renamed your files and folders as you like. E.g. if you renamed the `web` folder with the static files that Crossbar.io should serve, you'll need to adjust the Crossbar.io node configuration as well, so it knows where your stuff is. But it doesn't care how you name it.

Another note: the `hello:python` app generated is actually more complex than it needs to be for the bare minimum - it will create a whole Python *package* structure (e.g. with `setup.py` and stuff). Which can be convenient, but is more than the bare minimum required.

**Comment by JuliaRakitina** [comment]
Thank you. I am using AutobahnPython for my server stuff and Angular wrapper for AutobahnJs for my server and it works fine for now. I never used WAMP before and I think this is great, despite my little confusing

**Comment by oberstet** [comment]
@JuliaRakitina So you are using https://github.com/voryx/angular-wamp ? I'd be really interested on feedback/experience on this! If you like, join the mailing list (https://groups.google.com/forum/#!forum/autobahnws) and talk a little about your projects and what you are doing. Would be fun, people are nice there and always interested in what others are doing.

**Comment by funnydoggie** [comment]
@oberstet followed the crossbar install guidelines (pypy...all the way to checking version), then get the following error (I tried removing and reinstalling pip cryptography), but still get error: Cannot load library ~/pypy-2.5-linux_x86_64-portable/site-packages/cryptography/_Cryptography_cffi_f3e4673fx399b1113.pypy-25.so: ~/pypy-2.5-linux_x86_64-portable/site-packages/cryptography/_Cryptography_cffi_f3e4673fx399b1113.pypy-25.so: symbol EC_GFp_nistp521_method, version OPENSSL_1.0.1 not defined in file libcrypto.so.1.0.0 with link time reference

**Comment by oberstet** [comment]
Are you using a Linux version and distribution listed on the PyPy website as supported? Looks a bit like the OpenSSL linked at run-time is at a different version than what the PyPy was built against.

**Comment by funnydoggie** [comment]
thanks for responding so quickly:)
fresh install of Ubuntu 14.04.2 LTS. And before I followed steps at http://crossbar.io/docs/Installation-on-Linux/ I did visit pypy to see ifpypy-2.5-linux_x86_64 was the latest version (which it appeared to be)
I just visited pypy to see if my version was supported, but my version is such a generic I assumed OK (but could not find specifically).
I followed the steps in order and at the same time, but now I read them closely, I see libssl-dev is installed first with apt-get, but the pypy is a virtual environment, right?

**Comment by oberstet** [comment]
actually, for that specific Ubuntu (which is I guess nowerdays one of the most common Linux distros in use), you might try out the brand new binary packages http://crossbar.io/docs/Installation-on-Ubuntu/ - These come with pre-bundled / integrated PyPy, Twisted, Autobahn, Crossbar.io and all dependencies for a full Crossbar.io - including all optional features.

**Comment by funnydoggie** [comment]
that looks awesome and simple! Do you suggest I first undo all the steps I followed up to version check? (i.e. remove pip packages, pip, pypy and apt-get remove everything?

**Comment by oberstet** [comment]
no, it's fine as it is for starting the Ubuntu specific installation from binary packages. What you did was just installing some standard Ubuntu packages that won't hurt anyway, plus a PyPy in a dedicated directory that you can just throw away.

**Comment by oberstet** [comment]
wait, you need different URLs still :(

**Comment by funnydoggie** [comment]
was working great until "unable to locate package crossbar"...

**Comment by oberstet** [comment]
this URL should do (need to setup the DNS redirect still .. sorry): `http://crossbarpkg.s3-website-eu-west-1.amazonaws.com/ubuntu`instead of `http://package.crossbar.io/ubuntu`

**Comment by funnydoggie** [comment]
SUCCESS!
But you may be interested that after apt-get update "failed to get http://crossbarpkg.s3-website-eu-west-1.amazonaws.com/ubuntu/dists/trusty/InRelease"
Also, should I get delete the old repo I put in, or not worry?

**Comment by funnydoggie** [comment]
After midnight in Erlangan, time to sleep. Here in NY only 19:30. Thanks for your help -- good WE.

**Comment by funnydoggie** [comment]
I tried hello:python. Works great after following the new install. Before I noticed it was closed, I posted to the end of issue #306 the same issue as Julia was having above.

How to change default port for crossbar start? I had another Twisted server using 8080, so I tried --web=80 and other flags as work with twisted. Manually changed the port to 80 in index.html, but of course that is not where crossbar starts from, which still said "port 8080 in use".

I also tried hello:cpp but can't get scons to compile. From reading the cpp file, I could see I needed BOOST and once I exported the include path, I thought it'd compile. But scons compilation stops when it can't find msgpack.hpp, which I have. I use msgpack for C++11, so I just add msgpack/include to my include paths and it usually works. Before I exported the path, first error stops from SConstruct. But even after I export the msgpack path, I then get an error from failure to find it as an indirect include, not from hello.cpp, but from autobahn.hpp dependency included within hello.cpp.

**Comment by goeddea** [comment]
You set the port via the crossbar config (.crossbar/config.json) as part of the transport configuration. There's no possibility to set this via flags on the command line.

**Comment by funnydoggie** [comment]
Thanks goeddea; I see from .crossbar/config.json that I must set "web" type as well as "rawsocket" (8090) if I wish to move away from default ports. And then I assume I manually update ports in the cpp (or python or whatever) session variables in the remote procedures to match crossbar. I might have missed this in the docs, and if so, excuse me! But if not, perhaps others also may benefit from a short note pointing it out in the getting started.

**Comment by funnydoggie** [comment]
Still having scons build problem for hellocpp. Things I did: apt-get removed boost, and followed the tavendo instructions to install boost (I didn't use trunk, because latest 1.57 I think supports when_all and when_any). I also installed msgpack rather than leaving it header-only. This helped move along the build process, however, I still get scons error: http://pastebin.com/pTB0z5Y0

**Comment by funnydoggie** [comment]
...I see that mostly they are warnings, and the actual error that stops the build is error: 'DOUBLE' is not a member of 'msgpack::v1::type'. From searching Tavendo, I see this is also referenced in /AutobahnCpp/issues/30. Workaround there suggests compiling msgpack with flag and editing SConstruct.
Is this the only way, or can I simply change the type in autobahn_impl.hpp:539:15?
I'm also wondering if I'm doing something else wrong as how else is anyone else compiling the cpp version without also encountering this build error?

**Comment by funnydoggie** [comment]
SUCCESS! Jens Kristian Jensen's comment and fix is critical: https://groups.google.com/forum/#!msg/autobahnws/TAIS_p2wMBc/iJe7dk3bxGEJ Thanks Tobias for linking to it (autobahncpp/issues/30) so at least it can be found.
guys: can I help by editing the autobahncpp getting started for you? I think the addition of just a few lines of guidance will save people hours. It's because crossbar is developing so fast, but there's sure to be would-be-advocates who'll simply give up. I've already drunk the autobahn cool-aid, and I got the python hello remote procedure call to work, and I'm somewhat experienced with CMAKE and C++, so I perservered. My guess is that others will or are giving up, which seems like an avoidable problem for the team there! (for some odd reason I get a blank white screen at the URL chat.freenode.net, otherwise I would have offered to help on the #autobahn channel)

**Comment by meejah** [comment]
I'm sure a pull-request would be appreciated and rapidly merged by @oberstet 

If you mean the page at crossbar.io then you can find the Markdown content here:
https://github.com/crossbario/crossbarwww

**Comment by oberstet** [comment]
@funnydoggie Oh yes, adding more hints or docs would be highly welcome! If it concerns AutobahnCpp "docs", best would be a pull request against that repo. If it concerns Crossbar.io docs, as @meejah mentions, a PR against crossbarwww would be great.

**Comment by funnydoggie** [comment]
The question "Which docs" is itself part of the area that perhaps needs help (as @oberstet mentions several places!) it can be difficult for newcomers to see relationship between parts, i.e. crossbar, AutobahnCpp and now I'm working on crossbar postgres. Not sure why postgres example is under crossbar (which needs the three files to work), rather than just Autobahn, which one might think would be under autobahn python (although there is an "under dev" reference to postgres in autobahn|js). The link I'm working from http://crossbar.io/docs/Database-Programming-with-PostgreSQL/ appears to be an example that one might expect to find as a crossbar template (but when one lists templates, one realizes the templates are all "node" templates, which is why it's not there perhaps). Once I get postgres working (I started an issue in correct place) I'll be better able to help with pull-requests in the right repos.

**Comment by funnydoggie** [comment]
@oberstet : trying to get to the bottom of why crossbar ImportError: No module named psycopg2._psycopg.
Tried adding "import psycopg2" to my working crossbar pub/sub python example (hello) and this causes the import error. IHowever, I can import psycopg2 without problem from python interpreter, twisted and autobahn files.

**Comment by funnydoggie** [comment]
Is there a better place/channel to ask about crossbar imporing modules?..I've asked over at #autobahn, but not getting any replies there or here. Adding path to module in .pth file in crossbar/site-packages didn't fix.

**Comment by oberstet** [comment]
the examples have been cleaned up, and there is an awesome way of running almost all of them with one command now (credits: @meejah ):

```
cd examples
make examples
```

so closing ..
